# Generated by Django 3.2.21 on 2023-11-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_auto_20231129_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealjournalentry',
            old_name='quantity',
            new_name='meal',
        ),
        migrations.RemoveField(
            model_name='mealjournalentry',
            name='custom_food_items',
        ),
        migrations.RemoveField(
            model_name='mealjournalentry',
            name='predefined_food_items',
        ),
    ]
