# Generated by Django 3.2.21 on 2023-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20231201_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_days',
            field=models.PositiveIntegerField(default=12, help_text='Enter the number of days for returns'),
            preserve_default=False,
        ),
    ]
