# Generated by Django 3.2.21 on 2023-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_return_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='material_composition',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester')], default='Cotton', max_length=100),
        ),
    ]
