# Generated by Django 3.2.21 on 2023-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20231201_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_composition',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Plastic', 'Plastic'), ('Metal', 'Metal'), ('Elastic', 'Elastic'), ('Pvc', 'Pvc'), ('Foam', 'Foam')], default='Cotton', max_length=100),
        ),
    ]
