# Generated by Django 3.2.21 on 2023-10-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Keychains', 'Keychains'), ('Wriststraps', 'Wriststraps'), ('Yogamats', 'Yogamats'), ('Foamrollers', 'Foamrollers'), ('Protein', 'Protein'), ('Creatine', 'Creatine'), ('Electrolytes', 'Electrolytes'), ('Preworkout', 'Preworkout'), ('Postworkout', 'Postworkout')], default='Men', max_length=255),
        ),
    ]
