# Generated by Django 3.2.21 on 2023-12-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('message_subject', models.CharField(max_length=400)),
                ('message', models.TextField()),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('reply_sent', models.BooleanField(default=False)),
                ('regarding', models.CharField(choices=[('refunds', 'Refunds'), ('vouchers', 'Vouchers'), ('products', 'Products'), ('other reason', 'Other reason')], default='Select', max_length=24)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
